<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9f6dea823a63a63398b9bdc6f827421b
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MV\\SocialAuth\\' => 14,
        ),
        'H' => 
        array (
            'Hybridauth\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MV\\SocialAuth\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/Classes',
        ),
        'Hybridauth\\' => 
        array (
            0 => __DIR__ . '/..' . '/hybridauth/hybridauth/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9f6dea823a63a63398b9bdc6f827421b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9f6dea823a63a63398b9bdc6f827421b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
