<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'MV\\SocialAuth\\' => array($baseDir . '/Classes'),
    'Hybridauth\\' => array($vendorDir . '/hybridauth/hybridauth/src'),
);
